image: gitpod/workspace-postgres

tasks:
  - name: install postgresql
    init: |
      docker-compose up -d
      docker ps -a
  - name: install npm
    init: |
      cd hello-prisma/
      npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev
    env:
      DATABASE_URL: postgres://gitpod@localhost/posts
  - name: Prisma studio
    init: |
      cd hello-prisma/
      npx prisma studio
    env:
      DATABASE_URL: postgres://gitpod@localhost/posts
  - name: Run express server
    init: |
      cd hello-prisma/
      npm run dev
ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore
  - port: 5555
    onOpen: open-browser

vscode:
  extensions:
    - prisma.prisma
    - bradlc.vscode-tailwindcss
    - mikestead.dotenv
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-vscode.sublime-keybindings